# Generated by Django 4.1.1 on 2022-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='threads',
            old_name='scrapped_time',
            new_name='scrapped_date',
        ),
        migrations.RenameField(
            model_name='threads_replys',
            old_name='scrapped_time',
            new_name='scrapped_date',
        ),
    ]
