# Generated by Django 4.1.1 on 2022-09-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target_site',
            old_name='site_url',
            new_name='url_to_scrapp',
        ),
    ]
