# Generated by Django 4.1.1 on 2022-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_rename_site_url_target_site_url_to_scrapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_site',
            name='url_to_scrapp',
            field=models.URLField(max_length=100),
        ),
    ]
