# Generated by Django 4.1.1 on 2022-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_target_site_url_to_scrapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_site',
            name='name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
