# Generated by Django 4.1.1 on 2022-09-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_target_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads_replys',
            name='number_of_replys',
        ),
        migrations.RemoveField(
            model_name='threads_replys',
            name='title',
        ),
    ]
