# Generated by Django 4.1.1 on 2022-10-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_remove_threads_replys_number_of_replys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=75)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('scrapped_date', models.DateTimeField()),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.target_site')),
            ],
        ),
    ]
